### ISSUE TITLE
edit-properties command line example incorrect

### ISSUE THREAD

**Issue by veggiespam** [Contrast-Security-OSS/docs#101]
In both https://docs.contrastsecurity.com/admin_tsconfig.html#encrypt and https://docs.contrastsecurity.com/admin_tsconfig.html#backup , the command line example shows:  

```
contrast@TeamServer:~/contrast/bin$ ./edit-properties -o jdbc.port -e ../data/esapi/ -f ../data/conf/ad.properties
```

Both should be "-o -p" instead.

**Comment by SteveFeldman** [comment]
Thanks @veggiespam...we will take a look and make a fix...

**Comment by terra4383** [comment]
Fixed!
