### ISSUE TITLE
Custom Rule How-to updates

### ISSUE THREAD

**Issue by veggiespam** [Contrast-Security-OSS/docs#111]
The section https://docs.contrastsecurity.com/user_tsguideapp.html#rules is basically "whats new" and "animated gifs".  

there needs to be instructions on how to use it.  when the rules propagate outwards, etc etc.

**Comment by terra4383** [comment]
I have added a ticket to our ongoing Documentation update effort. Thanks.

**Comment by terra4383** [comment]
This has been updated.
