### ISSUE TITLE
Configuring LDAP Authentication is Duplicated

### ISSUE THREAD

**Issue by kevinfealey** [Contrast-Security-OSS/docs#166]
The _Configuring LDAP Authentication_ section seems to be duplicated in the docs. 
https://docs.contrastsecurity.com/admin_tsconfig.html#ldap points to the first entry, which is immediately followed by an entry with the same name, which appears to be identical.

**Comment by terra4383** [comment]
Whoops! Thanks for bringing this to our attention. The bug has been fixed.
