### ISSUE TITLE
Screenshot of old UI

### ISSUE THREAD

**Issue by kevinfealey** [Contrast-Security-OSS/docs#167]
The screenshot of the "Organization View" on https://docs.contrastsecurity.com/user_tsguideui.html#overview uses the old Contrast UI/colors. I think the buttons are all the same, so minimal impact - just might be confusing to new users to see the old color scheme.

**Comment by kevinfealey** [comment]
The "System Administration view" screenshot on the same page also uses the old UI.

**Comment by terra4383** [comment]
Thanks Kevin, you must be a mind-reader, as we are currently in the process of updating these already! The new images will be up later today.

**Comment by kevinfealey** [comment]
Sounds good, Terra! I just found another old screenshot - would you like me to continue to update this ticket or do you already have a list of images to update?

**Comment by terra4383** [comment]
Kevin, we pushed several image updates today so maybe take another look and see if it's been addressed already. If you still see outdated images a new ticket would be great, thanks!
