### ISSUE TITLE
Java Agent System Properties - General Properties

### ISSUE THREAD

**Issue by davewichers** [Contrast-Security-OSS/docs#178]
Please add an example of exactly how to change one of these properties at the command line when launching the java agent? For example, show someone using:  -Dcontrast.override.appname=<app name> when launching the java agent (e.g., -javaagent:path/to/contrast.jar).  i.e., does it go after the -javagent? Before? Doesn't matter??

**Comment by terra4383** [comment]
This has been addressed, thanks.

**Comment by davewichers** [comment]
Thanks. I noticed it says this at the bottom of the open docs pages:
Copyright © 2013-2016. Might want to increment the year.

**Comment by terra4383** [comment]
Thank you 👍
