### ISSUE TITLE
Add HTML-link-anchors to all H1/H2/H3

### ISSUE THREAD

**Issue by veggiespam** [Contrast-Security-OSS/docs#21]
```
I want to tell a user to "for more information, read this
link".  However, the pages are long and I need to tell 
users "go to this page here and then scroll until you
see this section titled XYZ."

Add some user friendliness.  For all <h1> <h2>, 
add an HTML <a id="abc" name="abc" class="anchor">.  
You do this now for some <h1> elements.  I want this 
also for all <h2> elements.  

Also, add a clickable icon that exists in the <h1><h2> titles.  
So, I can click on that icon and it takes me to this anchor tag 
or it copies the URL#tag into the pasteboard.  Thus, it is easy
to copy the URL for sending to my users.
```

**Comment by terra4383** [comment]
Hi there!  FYI, if you click on the article title in the side navigation menu, there are anchor points that will jump to the desired article and you can obtain the direct URL for sharing.

![anchors](https://cloud.githubusercontent.com/assets/13530945/11539464/28a0c380-98f5-11e5-82e1-572e5a0ccf3b.png)

**Comment by veggiespam** [comment]
That only works to H1.  I'd like to see at H2.

**Comment by veggiespam** [comment]
For example, the "How to add line numbers to .Net Contrast reports" has been a common question for me.  I'd like a direct link to that H2.

**Comment by terra4383** [comment]
Ok, thank you for the example - we will look into the possibility of doing this as soon as we can.

**Comment by terra4383** [comment]
Hello, I wanted to update you that we have done some initial investigation into this functionality. We will continue to consider it moving forward, but as we may be making significant updates to the site in the future, it’s not high priority to implement this right now in the site's current state.  Thanks again for this suggestion!
