### ISSUE TITLE
Clarify Difference between API 1 and API 2

### ISSUE THREAD

**Issue by davewichers** [Contrast-Security-OSS/docs#31]
Can you add some clarification in both introductions as to the difference between the two versions and which I should use? If API 1 docs are simply obsolete, just say that so people can ignore them and only look at 2.

**Comment by terra4383** [comment]
Ok thanks, we will work on this.

**Comment by davewichers** [comment]
This has been open for a long time. Has it already been addressed? I reported a couple other issues around the same time, so can you look into those too?

**Comment by terra4383** [comment]
Hi Dave,
Thanks for following up. We have addressed a couple of things but will make time to look back at these issues again either this sprint or next.

**Comment by terra4383** [comment]
Hi Dave, sorry for the delay. I have created a ticket to tackle this in Q1, which will include creating a roadmap for API support as well as messaging statements around v1-4. Thank you!
