### ISSUE TITLE
Java Agent Documentation needs a High Level Custom Rules Section

### ISSUE THREAD

**Issue by davewichers** [Contrast-Security-OSS/docs#32]
Seems like there should be a higher level documentation topic called Custom Rules that is a peer to Troubleshooting (Similar to under .NET that has Level 2 Rules).

And under it, it should have an introduction that explains Level 2 and Level 3 rules. And then sections on Level 2 and Level 3 rules. The article: "How To Add A Level 2 Rule" should be moved under the Custom Rules section, as should: Advanced Rules Customization, that is currently under Configuration.

Seems like there really should be an outline something like this:
- Introduction:
- Writing Custom Level 2 Rules
- Configuring Contrast to Use Custom Level 2 Rules
- Writing Custom Level 3 Rules
- Example Level 3 Rules (With different examples for different scenarios)
  *\* Like how to flag ALL uses of any method in a specific class or package
  *\* How to flag instantiation of a subclass of a specific class
  *\* Others you already have.
- Configuring Contrast to Use Custom Level 3 Rules

**Comment by terra4383** [comment]
This makes sense, thanks. We will work on this ASAP.

**Comment by terra4383** [comment]
Hi Dave, we did make some updates to this awhile ago but Product management will be discussing it further. You will be included in a forthcoming email from Steve. Thanks!
