### ISSUE TITLE
Image on: Downloading TeamServer From Contrast HUB too small

### ISSUE THREAD

**Issue by davewichers** [Contrast-Security-OSS/docs#34]
There is a warning message on this page (https://docs.contrastsecurity.com/admin_tsinstall.html#download), but its too small. Can it be made bigger so you don't have to click on it to read it?

**Comment by terra4383** [comment]
All thumbnail images (such as this warning message) can be clicked on and viewed at full size.

**Comment by davewichers** [comment]
Right. I get that. But it would be better if it could be read without having to click on it. If you have to click on a text image to read it, I'd suggest you convert the text image to simply text so it can be read without having to click on it.
