### ISSUE TITLE
Please add introductions to the Developer/Administrator/User sections

### ISSUE THREAD

**Issue by davewichers** [Contrast-Security-OSS/docs#37]
To help readers understand what you mean by these three roles, can you add intro sections for each of these to help explain how your have the documentation organized by these role. This should help make it easier for readers to understand the roles/organization scheme and thus find the right role to look under for documentation they are looking for.

**Comment by SteveFeldman** [comment]
This is a good suggestion Dave...

**Comment by terra4383** [comment]
Hi Dave.  After discussing with Steve, we understand and agree with this suggestion; however, we may be reworking the IA in Q1 and it's likely we would move away from this persona-based structure. We'll keep you in the loop but we're going to hold off on this right now, thank you!
