### ISSUE TITLE
Vulnerability PDF report instructions are outdated

### ISSUE THREAD

**Issue by cgtwin** [Contrast-Security-OSS/docs#4]
User > Teamserver > Guide > Report 
@SteveFeldman instructions are no longer valid for new UI

**Comment by SteveFeldman** [comment]
Thanks for the commenting on the issue. We have a few docs that are outdated as we migrated from Zendesk to Open-Docs. Looks like this one made it past the goalie. We will fix it this sprint.

**Comment by terra4383** [comment]
Article has been updated.
