### ISSUE TITLE
Top header menu options disappear on small screens

### ISSUE THREAD

**Issue by cgtwin** [Contrast-Security-OSS/docs#7]
![header_bug](https://cloud.githubusercontent.com/assets/13968137/10823258/6ab361be-7e20-11e5-863c-ab76a37f3f0f.png)

**Comment by terra4383** [comment]
Thanks for bringing this to our attention. We will address it ASAP.

**Comment by terra4383** [comment]
<img width="843" alt="topnavmenu1" src="https://cloud.githubusercontent.com/assets/13530945/11542328/e0c1647e-9904-11e5-891e-0b9e699bacef.png">
<img width="843" alt="topnavmenu2" src="https://cloud.githubusercontent.com/assets/13530945/11542329/e0c5e828-9904-11e5-8e3b-55d3a013e72a.png">
