### ISSUE TITLE
Generic webhook placeholders

### ISSUE THREAD

**Issue by sethjackson** [Contrast-Security-OSS/docs#711]
Would it be possible to list all the placeholders that are supported in generic webhooks in [these docs](https://github.com/Contrast-Security-OSS/docs/blob/master/content/admin/org_settings/integrations/GenericWebhook.md) along with what they get expanded to?

Currently it's not very clear if the `$Title` and `$Message` placeholders are the only ones supported and it is not clear what they expand to.

Maybe something like this would work?

| Placeholder   | Value                      |
| ------------- |---------------------|
| `$Title`          | value it expands to |
| `$Message`   | value it expands to |

**Comment by kaitlynmortimer** [comment]
Thanks for the suggestion! Your dedicated Customer Success Manager has been in touch regarding this issue.
